pub enum OpData {
    ADC,
    ADD,
    AND,
    BIT,
    CP,
    CPL,
    DAA,
    DEC,
    INC,
    LD,
    LDH,
    LDHL,
    OR,
    POP,
    PUSH,
    RES,
    RL,
    RLC,
    RR,
    RRC,
    SBC,
    SET,
    SLA,
    SRA,
    SRL,
    SUB,
    SWAP,
    XOR,
}

pub enum Reg {
    A,B,C,D,E,H,L,
    AF,BC,DE,HL,SP,
    IMM8,
    IMM16,
    Unused,
}

pub enum Acc {
    DIR,
    IND,
    IND_INC,
    IND_DEC,
}

pub enum OpJump {
    JP,
    JR,
    CALL,
    RET,
    RETI,
    RST,
}

pub enum JumpCondition {
    ALWAYS,
    C,
    NC,
    Z,
    NZ,
}

pub enum FlagOp {
    Unaffected,
    SetFlag,
    ResetFlag,
    CalculateFlag,
}

pub enum Instruction {
    DATA16 {mnemo: &'static str, length:u8, cycles:u8, op: OpData, dst:Reg, dst_access:Acc, src:Reg, src_access:Acc, z:FlagOp, n:FlagOp, h:FlagOp, c:FlagOp},
    DATA8 {mnemo: &'static str, length:u8, cycles:u8, op: OpData, dst:Reg, dst_access:Acc, src:Reg, src_access:Acc, z:FlagOp, n:FlagOp, h:FlagOp, c:FlagOp, bit:u8},
    JUMP  {mnemo: &'static str, length:u8, cycles:u8, op: OpJump, cond: JumpCondition, rst_target:u8},
    PREFIX  {mnemo: &'static str, length:u8, cycles:u8},
    SCF  {mnemo: &'static str, length:u8, cycles:u8},
    CCF  {mnemo: &'static str, length:u8, cycles:u8},
    DI  {mnemo: &'static str, length:u8, cycles:u8},
    EI  {mnemo: &'static str, length:u8, cycles:u8},
    HALT  {mnemo: &'static str, length:u8, cycles:u8},
    NOP  {mnemo: &'static str, length:u8, cycles:u8},
    STOP  {mnemo: &'static str, length:u8, cycles:u8},
    UNDEF {mnemo: &'static str,},
}

use Instruction::*;
use OpData::*;
use Reg::*;
use Acc::*;
use OpJump::*;
use FlagOp::*;

pub const instructions: [Instruction;0x200] = [
NOP {mnemo: "NOP", length: 1u8, cycles: 4u8, },
DATA16 {mnemo: "LD BC,d16", length: 3u8, cycles: 12u8, op: LD, dst: BC, dst_access: DIR, src: IMM16, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "LD (BC),A", length: 1u8, cycles: 8u8, op: LD, dst: BC, dst_access: IND, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "INC BC", length: 1u8, cycles: 8u8, op: INC, dst: BC, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC B", length: 1u8, cycles: 4u8, op: INC, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC B", length: 1u8, cycles: 4u8, op: DEC, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,d8", length: 2u8, cycles: 8u8, op: LD, dst: B, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "RLCA", length: 1u8, cycles: 4u8, op: RLC, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA16 {mnemo: "LD (a16),SP", length: 3u8, cycles: 20u8, op: LD, dst: IMM16, dst_access: IND, src: SP, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA16 {mnemo: "ADD HL,BC", length: 1u8, cycles: 8u8, op: ADD, dst: HL, dst_access: DIR, src: BC, src_access: DIR, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, },
DATA8 {mnemo: "LD A,(BC)", length: 1u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: BC, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "DEC BC", length: 1u8, cycles: 8u8, op: DEC, dst: BC, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC C", length: 1u8, cycles: 4u8, op: INC, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC C", length: 1u8, cycles: 4u8, op: DEC, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,d8", length: 2u8, cycles: 8u8, op: LD, dst: C, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "RRCA", length: 1u8, cycles: 4u8, op: RRC, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
STOP {mnemo: "STOP 0", length: 2u8, cycles: 4u8, },
DATA16 {mnemo: "LD DE,d16", length: 3u8, cycles: 12u8, op: LD, dst: DE, dst_access: DIR, src: IMM16, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "LD (DE),A", length: 1u8, cycles: 8u8, op: LD, dst: DE, dst_access: IND, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "INC DE", length: 1u8, cycles: 8u8, op: INC, dst: DE, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC D", length: 1u8, cycles: 4u8, op: INC, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC D", length: 1u8, cycles: 4u8, op: DEC, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,d8", length: 2u8, cycles: 8u8, op: LD, dst: D, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "RLA", length: 1u8, cycles: 4u8, op: RL, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "JR r8", length: 2u8, cycles: 12u8, op: JR, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
DATA16 {mnemo: "ADD HL,DE", length: 1u8, cycles: 8u8, op: ADD, dst: HL, dst_access: DIR, src: DE, src_access: DIR, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, },
DATA8 {mnemo: "LD A,(DE)", length: 1u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: DE, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "DEC DE", length: 1u8, cycles: 8u8, op: DEC, dst: DE, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC E", length: 1u8, cycles: 4u8, op: INC, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC E", length: 1u8, cycles: 4u8, op: DEC, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,d8", length: 2u8, cycles: 8u8, op: LD, dst: E, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "RRA", length: 1u8, cycles: 4u8, op: RR, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "JR NZ,r8", length: 2u8, cycles: 8u8, op: JR, cond: JumpCondition::NZ, rst_target: 0u8, },
DATA16 {mnemo: "LD HL,d16", length: 3u8, cycles: 12u8, op: LD, dst: HL, dst_access: DIR, src: IMM16, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "LD (HL+),A", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND_INC, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "INC HL", length: 1u8, cycles: 8u8, op: INC, dst: HL, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC H", length: 1u8, cycles: 4u8, op: INC, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC H", length: 1u8, cycles: 4u8, op: DEC, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,d8", length: 2u8, cycles: 8u8, op: LD, dst: H, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DAA", length: 1u8, cycles: 4u8, op: DAA, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: Unaffected, h: ResetFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "JR Z,r8", length: 2u8, cycles: 8u8, op: JR, cond: JumpCondition::Z, rst_target: 0u8, },
DATA16 {mnemo: "ADD HL,HL", length: 1u8, cycles: 8u8, op: ADD, dst: HL, dst_access: DIR, src: HL, src_access: DIR, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, },
DATA8 {mnemo: "LD A,(HL+)", length: 1u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: HL, src_access: IND_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "DEC HL", length: 1u8, cycles: 8u8, op: DEC, dst: HL, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC L", length: 1u8, cycles: 4u8, op: INC, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC L", length: 1u8, cycles: 4u8, op: DEC, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,d8", length: 2u8, cycles: 8u8, op: LD, dst: L, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "CPL", length: 1u8, cycles: 4u8, op: CPL, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: SetFlag, h: SetFlag, c: Unaffected, bit: 0u8},
JUMP {mnemo: "JR NC,r8", length: 2u8, cycles: 8u8, op: JR, cond: JumpCondition::NC, rst_target: 0u8, },
DATA16 {mnemo: "LD SP,d16", length: 3u8, cycles: 12u8, op: LD, dst: SP, dst_access: DIR, src: IMM16, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "LD (HL-),A", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND_DEC, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "INC SP", length: 1u8, cycles: 8u8, op: INC, dst: SP, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC (HL)", length: 1u8, cycles: 12u8, op: INC, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC (HL)", length: 1u8, cycles: 12u8, op: DEC, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),d8", length: 2u8, cycles: 12u8, op: LD, dst: HL, dst_access: IND, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
SCF {mnemo: "SCF", length: 1u8, cycles: 4u8, },
JUMP {mnemo: "JR C,r8", length: 2u8, cycles: 8u8, op: JR, cond: JumpCondition::C, rst_target: 0u8, },
DATA16 {mnemo: "ADD HL,SP", length: 1u8, cycles: 8u8, op: ADD, dst: HL, dst_access: DIR, src: SP, src_access: DIR, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, },
DATA8 {mnemo: "LD A,(HL-)", length: 1u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: HL, src_access: IND_DEC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "DEC SP", length: 1u8, cycles: 8u8, op: DEC, dst: SP, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "INC A", length: 1u8, cycles: 4u8, op: INC, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "DEC A", length: 1u8, cycles: 4u8, op: DEC, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,d8", length: 2u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
CCF {mnemo: "CCF", length: 1u8, cycles: 4u8, },
DATA8 {mnemo: "LD B,B", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,C", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,D", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,E", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,H", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,L", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: B, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD B,A", length: 1u8, cycles: 4u8, op: LD, dst: B, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,B", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,C", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,D", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,E", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,H", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,L", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: C, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD C,A", length: 1u8, cycles: 4u8, op: LD, dst: C, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,B", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,C", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,D", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,E", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,H", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,L", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: D, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD D,A", length: 1u8, cycles: 4u8, op: LD, dst: D, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,B", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,C", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,D", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,E", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,H", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,L", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: E, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD E,A", length: 1u8, cycles: 4u8, op: LD, dst: E, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,B", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,C", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,D", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,E", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,H", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,L", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: H, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD H,A", length: 1u8, cycles: 4u8, op: LD, dst: H, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,B", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,C", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,D", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,E", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,H", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,L", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: L, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD L,A", length: 1u8, cycles: 4u8, op: LD, dst: L, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),B", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),C", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),D", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),E", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),H", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD (HL),L", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
HALT {mnemo: "HALT", length: 1u8, cycles: 4u8, },
DATA8 {mnemo: "LD (HL),A", length: 1u8, cycles: 8u8, op: LD, dst: HL, dst_access: IND, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,B", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: B, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,C", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: C, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,D", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: D, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,E", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: E, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,H", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: H, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,L", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: L, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,(HL)", length: 1u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: HL, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "LD A,A", length: 1u8, cycles: 4u8, op: LD, dst: A, dst_access: DIR, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA8 {mnemo: "ADD A,B", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,C", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,D", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,E", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,H", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,L", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,(HL)", length: 1u8, cycles: 8u8, op: ADD, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADD A,A", length: 1u8, cycles: 4u8, op: ADD, dst: A, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,B", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,C", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,D", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,E", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,H", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,L", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,(HL)", length: 1u8, cycles: 8u8, op: ADC, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "ADC A,A", length: 1u8, cycles: 4u8, op: ADC, dst: A, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB B", length: 1u8, cycles: 4u8, op: SUB, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB C", length: 1u8, cycles: 4u8, op: SUB, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB D", length: 1u8, cycles: 4u8, op: SUB, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB E", length: 1u8, cycles: 4u8, op: SUB, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB H", length: 1u8, cycles: 4u8, op: SUB, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB L", length: 1u8, cycles: 4u8, op: SUB, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB (HL)", length: 1u8, cycles: 8u8, op: SUB, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SUB A", length: 1u8, cycles: 4u8, op: SUB, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,B", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,C", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,D", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,E", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,H", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,L", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,(HL)", length: 1u8, cycles: 8u8, op: SBC, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SBC A,A", length: 1u8, cycles: 4u8, op: SBC, dst: A, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "AND B", length: 1u8, cycles: 4u8, op: AND, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND C", length: 1u8, cycles: 4u8, op: AND, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND D", length: 1u8, cycles: 4u8, op: AND, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND E", length: 1u8, cycles: 4u8, op: AND, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND H", length: 1u8, cycles: 4u8, op: AND, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND L", length: 1u8, cycles: 4u8, op: AND, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND (HL)", length: 1u8, cycles: 8u8, op: AND, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "AND A", length: 1u8, cycles: 4u8, op: AND, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR B", length: 1u8, cycles: 4u8, op: XOR, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR C", length: 1u8, cycles: 4u8, op: XOR, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR D", length: 1u8, cycles: 4u8, op: XOR, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR E", length: 1u8, cycles: 4u8, op: XOR, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR H", length: 1u8, cycles: 4u8, op: XOR, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR L", length: 1u8, cycles: 4u8, op: XOR, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR (HL)", length: 1u8, cycles: 8u8, op: XOR, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "XOR A", length: 1u8, cycles: 4u8, op: XOR, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR B", length: 1u8, cycles: 4u8, op: OR, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR C", length: 1u8, cycles: 4u8, op: OR, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR D", length: 1u8, cycles: 4u8, op: OR, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR E", length: 1u8, cycles: 4u8, op: OR, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR H", length: 1u8, cycles: 4u8, op: OR, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR L", length: 1u8, cycles: 4u8, op: OR, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR (HL)", length: 1u8, cycles: 8u8, op: OR, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "OR A", length: 1u8, cycles: 4u8, op: OR, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "CP B", length: 1u8, cycles: 4u8, op: CP, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP C", length: 1u8, cycles: 4u8, op: CP, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP D", length: 1u8, cycles: 4u8, op: CP, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP E", length: 1u8, cycles: 4u8, op: CP, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP H", length: 1u8, cycles: 4u8, op: CP, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP L", length: 1u8, cycles: 4u8, op: CP, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP (HL)", length: 1u8, cycles: 8u8, op: CP, dst: A, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "CP A", length: 1u8, cycles: 4u8, op: CP, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "RET NZ", length: 1u8, cycles: 8u8, op: RET, cond: JumpCondition::NZ, rst_target: 0u8, },
DATA16 {mnemo: "POP BC", length: 1u8, cycles: 12u8, op: POP, dst: BC, dst_access: DIR, src: SP, src_access: IND_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
JUMP {mnemo: "JP NZ,a16", length: 3u8, cycles: 12u8, op: JP, cond: JumpCondition::NZ, rst_target: 0u8, },
JUMP {mnemo: "JP a16", length: 3u8, cycles: 16u8, op: JP, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
JUMP {mnemo: "CALL NZ,a16", length: 3u8, cycles: 12u8, op: CALL, cond: JumpCondition::NZ, rst_target: 0u8, },
DATA16 {mnemo: "PUSH BC", length: 1u8, cycles: 16u8, op: PUSH, dst: SP, dst_access: IND_DEC, src: BC, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "ADD A,d8", length: 2u8, cycles: 8u8, op: ADD, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "RST 00H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
JUMP {mnemo: "RET Z", length: 1u8, cycles: 8u8, op: RET, cond: JumpCondition::Z, rst_target: 0u8, },
JUMP {mnemo: "RET", length: 1u8, cycles: 16u8, op: RET, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
JUMP {mnemo: "JP Z,a16", length: 3u8, cycles: 12u8, op: JP, cond: JumpCondition::Z, rst_target: 0u8, },
PREFIX {mnemo: "PREFIX CB", length: 1u8, cycles: 4u8, },
JUMP {mnemo: "CALL Z,a16", length: 3u8, cycles: 12u8, op: CALL, cond: JumpCondition::Z, rst_target: 0u8, },
JUMP {mnemo: "CALL a16", length: 3u8, cycles: 24u8, op: CALL, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
DATA8 {mnemo: "ADC A,d8", length: 2u8, cycles: 8u8, op: ADC, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "RST 08H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 8u8, },
JUMP {mnemo: "RET NC", length: 1u8, cycles: 8u8, op: RET, cond: JumpCondition::NC, rst_target: 0u8, },
DATA16 {mnemo: "POP DE", length: 1u8, cycles: 12u8, op: POP, dst: DE, dst_access: DIR, src: SP, src_access: IND_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
JUMP {mnemo: "JP NC,a16", length: 3u8, cycles: 12u8, op: JP, cond: JumpCondition::NC, rst_target: 0u8, },
UNDEF {mnemo: "UNDEF 211", },
JUMP {mnemo: "CALL NC,a16", length: 3u8, cycles: 12u8, op: CALL, cond: JumpCondition::NC, rst_target: 0u8, },
DATA16 {mnemo: "PUSH DE", length: 1u8, cycles: 16u8, op: PUSH, dst: SP, dst_access: IND_DEC, src: DE, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "SUB d8", length: 2u8, cycles: 8u8, op: SUB, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "RST 10H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 16u8, },
JUMP {mnemo: "RET C", length: 1u8, cycles: 8u8, op: RET, cond: JumpCondition::C, rst_target: 0u8, },
JUMP {mnemo: "RETI", length: 1u8, cycles: 16u8, op: RETI, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
JUMP {mnemo: "JP C,a16", length: 3u8, cycles: 12u8, op: JP, cond: JumpCondition::C, rst_target: 0u8, },
UNDEF {mnemo: "UNDEF 219", },
JUMP {mnemo: "CALL C,a16", length: 3u8, cycles: 12u8, op: CALL, cond: JumpCondition::C, rst_target: 0u8, },
UNDEF {mnemo: "UNDEF 221", },
DATA8 {mnemo: "SBC A,d8", length: 2u8, cycles: 8u8, op: SBC, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "RST 18H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 24u8, },
DATA8 {mnemo: "LDH (a8),A", length: 2u8, cycles: 12u8, op: LDH, dst: IMM8, dst_access: IND, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "POP HL", length: 1u8, cycles: 12u8, op: POP, dst: HL, dst_access: DIR, src: SP, src_access: IND_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "LD (C),A", length: 2u8, cycles: 8u8, op: LD, dst: C, dst_access: IND, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
UNDEF {mnemo: "UNDEF 227", },
UNDEF {mnemo: "UNDEF 228", },
DATA16 {mnemo: "PUSH HL", length: 1u8, cycles: 16u8, op: PUSH, dst: SP, dst_access: IND_DEC, src: HL, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "AND d8", length: 2u8, cycles: 8u8, op: AND, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8},
JUMP {mnemo: "RST 20H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 32u8, },
DATA16 {mnemo: "ADD SP,r8", length: 2u8, cycles: 16u8, op: ADD, dst: SP, dst_access: DIR, src: IMM8, src_access: DIR, z: ResetFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, },
JUMP {mnemo: "JP (HL)", length: 1u8, cycles: 4u8, op: JP, cond: JumpCondition::ALWAYS, rst_target: 0u8, },
DATA8 {mnemo: "LD (a16),A", length: 3u8, cycles: 16u8, op: LD, dst: IMM16, dst_access: IND, src: A, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
UNDEF {mnemo: "UNDEF 235", },
UNDEF {mnemo: "UNDEF 236", },
UNDEF {mnemo: "UNDEF 237", },
DATA8 {mnemo: "XOR d8", length: 2u8, cycles: 8u8, op: XOR, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
JUMP {mnemo: "RST 28H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 40u8, },
DATA8 {mnemo: "LDH A,(a8)", length: 2u8, cycles: 12u8, op: LDH, dst: A, dst_access: DIR, src: IMM8, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DATA16 {mnemo: "POP AF", length: 1u8, cycles: 12u8, op: POP, dst: AF, dst_access: DIR, src: SP, src_access: IND_INC, z: CalculateFlag, n: CalculateFlag, h: CalculateFlag, c: CalculateFlag, },
DATA8 {mnemo: "LD A,(C)", length: 2u8, cycles: 8u8, op: LD, dst: A, dst_access: DIR, src: C, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
DI {mnemo: "DI", length: 1u8, cycles: 4u8, },
UNDEF {mnemo: "UNDEF 244", },
DATA16 {mnemo: "PUSH AF", length: 1u8, cycles: 16u8, op: PUSH, dst: SP, dst_access: IND_DEC, src: AF, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "OR d8", length: 2u8, cycles: 8u8, op: OR, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
JUMP {mnemo: "RST 30H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 48u8, },
DATA16 {mnemo: "LD HL,SP+r8", length: 2u8, cycles: 12u8, op: LDHL, dst: HL, dst_access: DIR, src: IMM8, src_access: DIR, z: ResetFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, },
DATA16 {mnemo: "LD SP,HL", length: 1u8, cycles: 8u8, op: LD, dst: SP, dst_access: DIR, src: HL, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, },
DATA8 {mnemo: "LD A,(a16)", length: 3u8, cycles: 16u8, op: LD, dst: A, dst_access: DIR, src: IMM16, src_access: IND, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8},
EI {mnemo: "EI", length: 1u8, cycles: 4u8, },
UNDEF {mnemo: "UNDEF 252", },
UNDEF {mnemo: "UNDEF 253", },
DATA8 {mnemo: "CP d8", length: 2u8, cycles: 8u8, op: CP, dst: A, dst_access: DIR, src: IMM8, src_access: DIR, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8},
JUMP {mnemo: "RST 38H", length: 1u8, cycles: 16u8, op: RST, cond: JumpCondition::ALWAYS, rst_target: 56u8, },
DATA8 {mnemo: "RLC B", length: 2u8, cycles: 8u8, op: RLC, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC C", length: 2u8, cycles: 8u8, op: RLC, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC D", length: 2u8, cycles: 8u8, op: RLC, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC E", length: 2u8, cycles: 8u8, op: RLC, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC H", length: 2u8, cycles: 8u8, op: RLC, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC L", length: 2u8, cycles: 8u8, op: RLC, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC (HL)", length: 2u8, cycles: 16u8, op: RLC, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RLC A", length: 2u8, cycles: 8u8, op: RLC, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC B", length: 2u8, cycles: 8u8, op: RRC, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC C", length: 2u8, cycles: 8u8, op: RRC, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC D", length: 2u8, cycles: 8u8, op: RRC, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC E", length: 2u8, cycles: 8u8, op: RRC, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC H", length: 2u8, cycles: 8u8, op: RRC, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC L", length: 2u8, cycles: 8u8, op: RRC, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC (HL)", length: 2u8, cycles: 16u8, op: RRC, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RRC A", length: 2u8, cycles: 8u8, op: RRC, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL B", length: 2u8, cycles: 8u8, op: RL, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL C", length: 2u8, cycles: 8u8, op: RL, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL D", length: 2u8, cycles: 8u8, op: RL, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL E", length: 2u8, cycles: 8u8, op: RL, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL H", length: 2u8, cycles: 8u8, op: RL, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL L", length: 2u8, cycles: 8u8, op: RL, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL (HL)", length: 2u8, cycles: 16u8, op: RL, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RL A", length: 2u8, cycles: 8u8, op: RL, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR B", length: 2u8, cycles: 8u8, op: RR, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR C", length: 2u8, cycles: 8u8, op: RR, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR D", length: 2u8, cycles: 8u8, op: RR, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR E", length: 2u8, cycles: 8u8, op: RR, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR H", length: 2u8, cycles: 8u8, op: RR, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR L", length: 2u8, cycles: 8u8, op: RR, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR (HL)", length: 2u8, cycles: 16u8, op: RR, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "RR A", length: 2u8, cycles: 8u8, op: RR, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA B", length: 2u8, cycles: 8u8, op: SLA, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA C", length: 2u8, cycles: 8u8, op: SLA, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA D", length: 2u8, cycles: 8u8, op: SLA, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA E", length: 2u8, cycles: 8u8, op: SLA, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA H", length: 2u8, cycles: 8u8, op: SLA, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA L", length: 2u8, cycles: 8u8, op: SLA, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA (HL)", length: 2u8, cycles: 16u8, op: SLA, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SLA A", length: 2u8, cycles: 8u8, op: SLA, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRA B", length: 2u8, cycles: 8u8, op: SRA, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA C", length: 2u8, cycles: 8u8, op: SRA, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA D", length: 2u8, cycles: 8u8, op: SRA, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA E", length: 2u8, cycles: 8u8, op: SRA, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA H", length: 2u8, cycles: 8u8, op: SRA, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA L", length: 2u8, cycles: 8u8, op: SRA, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA (HL)", length: 2u8, cycles: 16u8, op: SRA, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRA A", length: 2u8, cycles: 8u8, op: SRA, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP B", length: 2u8, cycles: 8u8, op: SWAP, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP C", length: 2u8, cycles: 8u8, op: SWAP, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP D", length: 2u8, cycles: 8u8, op: SWAP, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP E", length: 2u8, cycles: 8u8, op: SWAP, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP H", length: 2u8, cycles: 8u8, op: SWAP, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP L", length: 2u8, cycles: 8u8, op: SWAP, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP (HL)", length: 2u8, cycles: 16u8, op: SWAP, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SWAP A", length: 2u8, cycles: 8u8, op: SWAP, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8},
DATA8 {mnemo: "SRL B", length: 2u8, cycles: 8u8, op: SRL, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL C", length: 2u8, cycles: 8u8, op: SRL, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL D", length: 2u8, cycles: 8u8, op: SRL, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL E", length: 2u8, cycles: 8u8, op: SRL, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL H", length: 2u8, cycles: 8u8, op: SRL, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL L", length: 2u8, cycles: 8u8, op: SRL, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL (HL)", length: 2u8, cycles: 16u8, op: SRL, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "SRL A", length: 2u8, cycles: 8u8, op: SRL, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8},
DATA8 {mnemo: "BIT 0,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 0,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "BIT 1,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 1,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "BIT 2,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 2,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "BIT 3,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 3,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "BIT 4,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 4,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "BIT 5,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 5,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "BIT 6,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 6,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "BIT 7,B", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: B, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,C", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: C, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,D", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: D, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,E", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: E, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,H", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: H, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,L", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: L, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,(HL)", length: 2u8, cycles: 16u8, op: BIT, dst: Unused, dst_access: DIR, src: HL, src_access: IND, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "BIT 7,A", length: 2u8, cycles: 8u8, op: BIT, dst: Unused, dst_access: DIR, src: A, src_access: DIR, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 0,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 0,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "RES 1,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 1,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "RES 2,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 2,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "RES 3,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 3,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "RES 4,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 4,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "RES 5,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 5,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "RES 6,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 6,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "RES 7,B", length: 2u8, cycles: 8u8, op: RES, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,C", length: 2u8, cycles: 8u8, op: RES, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,D", length: 2u8, cycles: 8u8, op: RES, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,E", length: 2u8, cycles: 8u8, op: RES, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,H", length: 2u8, cycles: 8u8, op: RES, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,L", length: 2u8, cycles: 8u8, op: RES, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,(HL)", length: 2u8, cycles: 16u8, op: RES, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "RES 7,A", length: 2u8, cycles: 8u8, op: RES, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 0,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 0,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0},
DATA8 {mnemo: "SET 1,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 1,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1},
DATA8 {mnemo: "SET 2,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 2,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2},
DATA8 {mnemo: "SET 3,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 3,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3},
DATA8 {mnemo: "SET 4,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 4,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4},
DATA8 {mnemo: "SET 5,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 5,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5},
DATA8 {mnemo: "SET 6,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 6,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6},
DATA8 {mnemo: "SET 7,B", length: 2u8, cycles: 8u8, op: SET, dst: B, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,C", length: 2u8, cycles: 8u8, op: SET, dst: C, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,D", length: 2u8, cycles: 8u8, op: SET, dst: D, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,E", length: 2u8, cycles: 8u8, op: SET, dst: E, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,H", length: 2u8, cycles: 8u8, op: SET, dst: H, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,L", length: 2u8, cycles: 8u8, op: SET, dst: L, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,(HL)", length: 2u8, cycles: 16u8, op: SET, dst: HL, dst_access: IND, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
DATA8 {mnemo: "SET 7,A", length: 2u8, cycles: 8u8, op: SET, dst: A, dst_access: DIR, src: Unused, src_access: DIR, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7},
];
