#[derive(Copy, Clone, PartialEq)]
pub enum OpData {
    ADC,
    ADD,
    AND,
    BIT,
    CP,
    CPL,
    DAA,
    DEC,
    INC,
    LD,
    LDH,
    LDHL,
    OR,
    POP,
    PUSH,
    RES,
    RL,
    RLC,
    RR,
    RRC,
    SBC,
    SET,
    SLA,
    SRA,
    SRL,
    SUB,
    SWAP,
    XOR,
}

#[derive(Copy, Clone, PartialEq)]
pub enum Location8 {
    Empty,
    A, B, C, D, E, H, L,
    IMM8,
    ADDR_BC, ADDR_DE, ADDR_HL,
    ADDR_HL_DEC, ADDR_HL_INC,
    ADDR_IMM16,
    ADDR_C, ADDR_IMM8,
}

#[derive(Copy, Clone, PartialEq)]
pub enum Location16 {
    Empty_W,
    AF, BC, DE, HL, SP, SP_IMM8,
    IMM16,
    ADDR_SP_DEC, ADDR_SP_INC,
    ADDR_IMM16_W,
}

#[derive(Copy, Clone, PartialEq)]
pub enum OpJump {
    JP,
    JR,
    CALL,
    RET,
    RETI,
    RST,
}

#[derive(Copy, Clone, PartialEq)]
pub enum JumpCondition {
    ALWAYS,
    C,
    NC,
    Z,
    NZ,
}

#[derive(Copy, Clone, PartialEq)]
pub enum FlagOp {
    Unaffected,
    SetFlag,
    ResetFlag,
    CalculateFlag,
}

#[derive(Copy, Clone, PartialEq)]
pub enum Operation {
    DATA16 {op: OpData, dst:Location16, src:Location16, z:FlagOp, n:FlagOp, h:FlagOp, c:FlagOp},
    DATA8 {op: OpData, dst:Location8, src:Location8, z:FlagOp, n:FlagOp, h:FlagOp, c:FlagOp, bit:u8},
    JUMP  {op: OpJump, cond: JumpCondition, rst_target:u8},
    PREFIX,
    SCF,
    CCF,
    DI,
    EI,
    HALT,
    NOP,
    STOP,
    UNDEF,
}

#[derive(Copy, Clone, PartialEq)]
pub struct Instruction {
    pub mnemo: &'static str,
    pub length:u8,
    pub cycles:u8,
    pub operation: Operation,
}

use Operation::*;
use OpData::*;
use Location8::*;
use Location16::*;
use OpJump::*;
use FlagOp::*;

pub const instructions: [Instruction;0x200] = [
Instruction {mnemo: "NOP", length: 1u8, cycles: 4u8, operation:NOP},
Instruction {mnemo: "LD BC,d16", length: 3u8, cycles: 12u8, operation:DATA16 {op: LD, dst: BC, src: IMM16, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "LD (BC),A", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_BC, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "INC BC", length: 1u8, cycles: 8u8, operation:DATA16 {op: INC, dst: BC, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC B", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC B", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: B, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: B, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "RLCA", length: 1u8, cycles: 4u8, operation:DATA8 {op: RLC, dst: A, src: Empty, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "LD (a16),SP", length: 3u8, cycles: 20u8, operation:DATA16 {op: LD, dst: ADDR_IMM16_W, src: SP, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "ADD HL,BC", length: 1u8, cycles: 8u8, operation:DATA16 {op: ADD, dst: HL, src: BC, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "LD A,(BC)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: ADDR_BC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC BC", length: 1u8, cycles: 8u8, operation:DATA16 {op: DEC, dst: BC, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC C", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC C", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: C, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: C, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "RRCA", length: 1u8, cycles: 4u8, operation:DATA8 {op: RRC, dst: A, src: Empty, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "STOP 0", length: 2u8, cycles: 4u8, operation:STOP},
Instruction {mnemo: "LD DE,d16", length: 3u8, cycles: 12u8, operation:DATA16 {op: LD, dst: DE, src: IMM16, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "LD (DE),A", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_DE, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "INC DE", length: 1u8, cycles: 8u8, operation:DATA16 {op: INC, dst: DE, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC D", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC D", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: D, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: D, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "RLA", length: 1u8, cycles: 4u8, operation:DATA8 {op: RL, dst: A, src: Empty, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "JR r8", length: 2u8, cycles: 12u8, operation:JUMP {op: JR, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "ADD HL,DE", length: 1u8, cycles: 8u8, operation:DATA16 {op: ADD, dst: HL, src: DE, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "LD A,(DE)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: ADDR_DE, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC DE", length: 1u8, cycles: 8u8, operation:DATA16 {op: DEC, dst: DE, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC E", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC E", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: E, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: E, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "RRA", length: 1u8, cycles: 4u8, operation:DATA8 {op: RR, dst: A, src: Empty, z: ResetFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "JR NZ,r8", length: 2u8, cycles: 8u8, operation:JUMP {op: JR, cond: JumpCondition::NZ, rst_target: 0u8, }},
Instruction {mnemo: "LD HL,d16", length: 3u8, cycles: 12u8, operation:DATA16 {op: LD, dst: HL, src: IMM16, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "LD (HL+),A", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL_INC, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "INC HL", length: 1u8, cycles: 8u8, operation:DATA16 {op: INC, dst: HL, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC H", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC H", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: H, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: H, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DAA", length: 1u8, cycles: 4u8, operation:DATA8 {op: DAA, dst: A, src: Empty, z: CalculateFlag, n: Unaffected, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "JR Z,r8", length: 2u8, cycles: 8u8, operation:JUMP {op: JR, cond: JumpCondition::Z, rst_target: 0u8, }},
Instruction {mnemo: "ADD HL,HL", length: 1u8, cycles: 8u8, operation:DATA16 {op: ADD, dst: HL, src: HL, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "LD A,(HL+)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: ADDR_HL_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC HL", length: 1u8, cycles: 8u8, operation:DATA16 {op: DEC, dst: HL, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC L", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC L", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: L, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: L, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "CPL", length: 1u8, cycles: 4u8, operation:DATA8 {op: CPL, dst: A, src: Empty, z: Unaffected, n: SetFlag, h: SetFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "JR NC,r8", length: 2u8, cycles: 8u8, operation:JUMP {op: JR, cond: JumpCondition::NC, rst_target: 0u8, }},
Instruction {mnemo: "LD SP,d16", length: 3u8, cycles: 12u8, operation:DATA16 {op: LD, dst: SP, src: IMM16, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "LD (HL-),A", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL_DEC, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "INC SP", length: 1u8, cycles: 8u8, operation:DATA16 {op: INC, dst: SP, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC (HL)", length: 1u8, cycles: 12u8, operation:DATA8 {op: INC, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC (HL)", length: 1u8, cycles: 12u8, operation:DATA8 {op: DEC, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),d8", length: 2u8, cycles: 12u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "SCF", length: 1u8, cycles: 4u8, operation:SCF},
Instruction {mnemo: "JR C,r8", length: 2u8, cycles: 8u8, operation:JUMP {op: JR, cond: JumpCondition::C, rst_target: 0u8, }},
Instruction {mnemo: "ADD HL,SP", length: 1u8, cycles: 8u8, operation:DATA16 {op: ADD, dst: HL, src: SP, z: Unaffected, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "LD A,(HL-)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: ADDR_HL_DEC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC SP", length: 1u8, cycles: 8u8, operation:DATA16 {op: DEC, dst: SP, src: Empty_W, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "INC A", length: 1u8, cycles: 4u8, operation:DATA8 {op: INC, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DEC A", length: 1u8, cycles: 4u8, operation:DATA8 {op: DEC, dst: A, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "CCF", length: 1u8, cycles: 4u8, operation:CCF},
Instruction {mnemo: "LD B,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: B, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD B,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: B, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: C, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD C,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: C, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: D, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD D,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: D, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: E, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD E,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: E, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: H, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD H,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: H, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: L, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD L,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: L, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),B", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),C", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),D", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),E", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),H", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD (HL),L", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "HALT", length: 1u8, cycles: 4u8, operation:HALT},
Instruction {mnemo: "LD (HL),A", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_HL, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: B, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: D, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: E, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: H, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: L, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: ADDR_HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "LD A,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: LD, dst: A, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "ADD A,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: B, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: C, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: D, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: E, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: H, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: L, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: ADD, dst: A, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADD A,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADD, dst: A, src: A, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: B, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: C, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: D, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: E, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: H, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: L, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: ADC, dst: A, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "ADC A,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: ADC, dst: A, src: A, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB B", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: B, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB C", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: C, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB D", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: D, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB E", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: E, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB H", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: H, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB L", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: L, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB (HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: SUB, dst: A, src: ADDR_HL, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SUB A", length: 1u8, cycles: 4u8, operation:DATA8 {op: SUB, dst: A, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,B", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: B, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,C", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: C, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,D", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: D, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,E", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: E, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,H", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: H, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,L", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: L, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,(HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: SBC, dst: A, src: ADDR_HL, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SBC A,A", length: 1u8, cycles: 4u8, operation:DATA8 {op: SBC, dst: A, src: A, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "AND B", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND C", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND D", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND E", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND H", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND L", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND (HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: AND, dst: A, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "AND A", length: 1u8, cycles: 4u8, operation:DATA8 {op: AND, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR B", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR C", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR D", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR E", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR H", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR L", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR (HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: XOR, dst: A, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "XOR A", length: 1u8, cycles: 4u8, operation:DATA8 {op: XOR, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR B", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR C", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR D", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR E", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR H", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR L", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR (HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: OR, dst: A, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "OR A", length: 1u8, cycles: 4u8, operation:DATA8 {op: OR, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "CP B", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: B, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP C", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: C, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP D", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: D, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP E", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: E, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP H", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: H, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP L", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: L, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP (HL)", length: 1u8, cycles: 8u8, operation:DATA8 {op: CP, dst: A, src: ADDR_HL, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "CP A", length: 1u8, cycles: 4u8, operation:DATA8 {op: CP, dst: A, src: Empty, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RET NZ", length: 1u8, cycles: 8u8, operation:JUMP {op: RET, cond: JumpCondition::NZ, rst_target: 0u8, }},
Instruction {mnemo: "POP BC", length: 1u8, cycles: 12u8, operation:DATA16 {op: LD, dst: BC, src: ADDR_SP_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "JP NZ,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: JP, cond: JumpCondition::NZ, rst_target: 0u8, }},
Instruction {mnemo: "JP a16", length: 3u8, cycles: 16u8, operation:JUMP {op: JP, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "CALL NZ,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: CALL, cond: JumpCondition::NZ, rst_target: 0u8, }},
Instruction {mnemo: "PUSH BC", length: 1u8, cycles: 16u8, operation:DATA16 {op: LD, dst: ADDR_SP_DEC, src: BC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "ADD A,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: ADD, dst: A, src: IMM8, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RST 00H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "RET Z", length: 1u8, cycles: 8u8, operation:JUMP {op: RET, cond: JumpCondition::Z, rst_target: 0u8, }},
Instruction {mnemo: "RET", length: 1u8, cycles: 16u8, operation:JUMP {op: RET, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "JP Z,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: JP, cond: JumpCondition::Z, rst_target: 0u8, }},
Instruction {mnemo: "PREFIX CB", length: 1u8, cycles: 4u8, operation:PREFIX},
Instruction {mnemo: "CALL Z,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: CALL, cond: JumpCondition::Z, rst_target: 0u8, }},
Instruction {mnemo: "CALL a16", length: 3u8, cycles: 24u8, operation:JUMP {op: CALL, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "ADC A,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: ADC, dst: A, src: IMM8, z: CalculateFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RST 08H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 8u8, }},
Instruction {mnemo: "RET NC", length: 1u8, cycles: 8u8, operation:JUMP {op: RET, cond: JumpCondition::NC, rst_target: 0u8, }},
Instruction {mnemo: "POP DE", length: 1u8, cycles: 12u8, operation:DATA16 {op: LD, dst: DE, src: ADDR_SP_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "JP NC,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: JP, cond: JumpCondition::NC, rst_target: 0u8, }},
Instruction {mnemo: "UNDEF 211", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "CALL NC,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: CALL, cond: JumpCondition::NC, rst_target: 0u8, }},
Instruction {mnemo: "PUSH DE", length: 1u8, cycles: 16u8, operation:DATA16 {op: LD, dst: ADDR_SP_DEC, src: DE, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "SUB d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: SUB, dst: A, src: IMM8, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RST 10H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 16u8, }},
Instruction {mnemo: "RET C", length: 1u8, cycles: 8u8, operation:JUMP {op: RET, cond: JumpCondition::C, rst_target: 0u8, }},
Instruction {mnemo: "RETI", length: 1u8, cycles: 16u8, operation:JUMP {op: RETI, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "JP C,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: JP, cond: JumpCondition::C, rst_target: 0u8, }},
Instruction {mnemo: "UNDEF 219", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "CALL C,a16", length: 3u8, cycles: 12u8, operation:JUMP {op: CALL, cond: JumpCondition::C, rst_target: 0u8, }},
Instruction {mnemo: "UNDEF 221", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "SBC A,d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: SBC, dst: A, src: IMM8, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RST 18H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 24u8, }},
Instruction {mnemo: "LDH (a8),A", length: 2u8, cycles: 12u8, operation:DATA8 {op: LDH, dst: ADDR_IMM8, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "POP HL", length: 1u8, cycles: 12u8, operation:DATA16 {op: LD, dst: HL, src: ADDR_SP_INC, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "LD (C),A", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: ADDR_C, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "UNDEF 227", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "UNDEF 228", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "PUSH HL", length: 1u8, cycles: 16u8, operation:DATA16 {op: LD, dst: ADDR_SP_DEC, src: HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "AND d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: AND, dst: A, src: IMM8, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "RST 20H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 32u8, }},
Instruction {mnemo: "ADD SP,r8", length: 2u8, cycles: 16u8, operation:DATA16 {op: LD, dst: SP, src: SP_IMM8, z: ResetFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "JP (HL)", length: 1u8, cycles: 4u8, operation:JUMP {op: JP, cond: JumpCondition::ALWAYS, rst_target: 0u8, }},
Instruction {mnemo: "LD (a16),A", length: 3u8, cycles: 16u8, operation:DATA8 {op: LD, dst: ADDR_IMM16, src: A, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "UNDEF 235", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "UNDEF 236", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "UNDEF 237", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "XOR d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: XOR, dst: A, src: IMM8, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "RST 28H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 40u8, }},
Instruction {mnemo: "LDH A,(a8)", length: 2u8, cycles: 12u8, operation:DATA8 {op: LDH, dst: A, src: ADDR_IMM8, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "POP AF", length: 1u8, cycles: 12u8, operation:DATA16 {op: LD, dst: AF, src: ADDR_SP_INC, z: CalculateFlag, n: CalculateFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "LD A,(C)", length: 1u8, cycles: 8u8, operation:DATA8 {op: LD, dst: A, src: ADDR_C, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "DI", length: 1u8, cycles: 4u8, operation:DI},
Instruction {mnemo: "UNDEF 244", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "PUSH AF", length: 1u8, cycles: 16u8, operation:DATA16 {op: LD, dst: ADDR_SP_DEC, src: AF, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "OR d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: OR, dst: A, src: IMM8, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "RST 30H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 48u8, }},
Instruction {mnemo: "LD HL,SP+r8", length: 2u8, cycles: 12u8, operation:DATA16 {op: LD, dst: HL, src: SP_IMM8, z: ResetFlag, n: ResetFlag, h: CalculateFlag, c: CalculateFlag, }},
Instruction {mnemo: "LD SP,HL", length: 1u8, cycles: 8u8, operation:DATA16 {op: LD, dst: SP, src: HL, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, }},
Instruction {mnemo: "LD A,(a16)", length: 3u8, cycles: 16u8, operation:DATA8 {op: LD, dst: A, src: ADDR_IMM16, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 0u8}},
Instruction {mnemo: "EI", length: 1u8, cycles: 4u8, operation:EI},
Instruction {mnemo: "UNDEF 252", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "UNDEF 253", length: 1u8, cycles: 0u8, operation:UNDEF},
Instruction {mnemo: "CP d8", length: 2u8, cycles: 8u8, operation:DATA8 {op: CP, dst: A, src: IMM8, z: CalculateFlag, n: SetFlag, h: CalculateFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RST 38H", length: 1u8, cycles: 16u8, operation:JUMP {op: RST, cond: JumpCondition::ALWAYS, rst_target: 56u8, }},
Instruction {mnemo: "RLC B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RLC, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RLC A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RLC, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RRC, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RRC A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RRC, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RL, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RL A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RL, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RR, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "RR A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RR, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SLA, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SLA A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SLA, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRA B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SRA, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRA A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRA, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SWAP, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SWAP A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SWAP, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: ResetFlag, bit: 0u8}},
Instruction {mnemo: "SRL B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: B, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: C, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: D, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: E, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: H, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: L, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL (HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SRL, dst: ADDR_HL, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "SRL A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SRL, dst: A, src: Empty, z: CalculateFlag, n: ResetFlag, h: ResetFlag, c: CalculateFlag, bit: 0u8}},
Instruction {mnemo: "BIT 0,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 0,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "BIT 1,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 1,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "BIT 2,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 2,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "BIT 3,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 3,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "BIT 4,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 4,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "BIT 5,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 5,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "BIT 6,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 6,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "BIT 7,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: B, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: C, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: D, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: E, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: H, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: L, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: BIT, dst: Empty, src: ADDR_HL, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "BIT 7,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: BIT, dst: Empty, src: A, z: CalculateFlag, n: ResetFlag, h: SetFlag, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 0,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 0,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "RES 1,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 1,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "RES 2,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 2,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "RES 3,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 3,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "RES 4,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 4,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "RES 5,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 5,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "RES 6,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 6,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "RES 7,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: RES, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "RES 7,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: RES, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 0,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 0,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<0}},
Instruction {mnemo: "SET 1,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 1,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<1}},
Instruction {mnemo: "SET 2,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 2,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<2}},
Instruction {mnemo: "SET 3,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 3,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<3}},
Instruction {mnemo: "SET 4,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 4,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<4}},
Instruction {mnemo: "SET 5,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 5,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<5}},
Instruction {mnemo: "SET 6,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 6,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<6}},
Instruction {mnemo: "SET 7,B", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: B, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,C", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: C, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,D", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: D, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,E", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: E, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,H", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: H, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,L", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: L, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,(HL)", length: 2u8, cycles: 16u8, operation:DATA8 {op: SET, dst: ADDR_HL, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
Instruction {mnemo: "SET 7,A", length: 2u8, cycles: 8u8, operation:DATA8 {op: SET, dst: A, src: Empty, z: Unaffected, n: Unaffected, h: Unaffected, c: Unaffected, bit: 1u8<<7}},
];
